<?php
/**
 * @file
 * Module file for custom behaviours and functions used by AFC
 * Basic hook implementations and helper functions will be found here.
 *
 *
 */

function afc_ess_node_view($node, $view_mode, $langcode) {

	if ($node->nid == 1) {
		
		global $user;
		$profile2 = profile2_load_by_user($user);
		$profile = $profile2['main'];
		$myval = $profile->field_badge[LANGUAGE_NONE][0]['value'];
		$mypin = $profile->field_pin[LANGUAGE_NONE][0]['value'];

		if ($mypin == '') {
			$text1 = '<div class="essWrapper">';
			$text1.= '<H2>Your account has not been configured to sign in to Attendance Enterprise.';
			$text1.= 'This could be because you have a manager account, or because your account has been left in-complete. ';
			$text1.= 'If you think this is in error, please contact the Tech Department at ext. 777 </h1>';
			$text1.= '</br>';
			$text1.='<h2>Thank you!</h2>';
			$text1.= '<div>';
		} else {
			$text1 = '<div class="essWrapper">';
			$text1.= "<iframe name=\"AE\" id=\"AE\" width=\"900\" height=\"650\" src=\"https://ashlandfood.attendanceondemand.com/ess/LOGIN?AE_BadgeID=$myval&AE_PIN=$mypin\" frameborder=\"0\"></iframe>";
			$text1.= '</div>';
			}

		$node->content['body'][0]['#markup'] = $text1;

}
}
